repos:
  - repo: local
    hooks:
      - id: build-web-ui
        name: Build Web UI
        entry: cd web/ && npm run build
        language: system
        files: '^web/.*\.(js|jsx|ts|tsx|css|scss|sass|html|json)$'
        stages: [commit]
        pass_filenames: false
        always_run: true
        verbose: true